models/Settings.php
<?php
namespace app\models;

use app\models\Accounts;
use app\models\OrdersStatuses;
use app\models\DeliveryTypes;
use app\models\Payments;
use app\models\OrderSync;

class Settings{
    public static function checkSettings(){
        $warning= false;
        
        if(!isset($_SESSION['clientId']) || $_SESSION['clientId'] ==''){
            return TRUE ;                
        }else{
            $clientId = $_SESSION['clientId'];
        }
        
        
        $status =  new \app\models\OrdersStatuses;
        $status = ($status::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$status::findAll(["uniqueAccountHash" => $clientId]);
        $delivery = new \app\models\DeliveryTypes;
        $delivery = ($delivery::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$delivery::findAll(["uniqueAccountHash" => $clientId]);
        $payments =  new \app\models\Payments();
        $payments = ($payments ::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$payments ::findAll(["uniqueAccountHash" => $clientId]);
        
        if($payments==null || $delivery==null || $status==null ){
            $warning = TRUE;            
        }
        return $warning;
    } 
}

models/settings.php
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

controllers/SettingsController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\RetailCRM;
use app\models\Storeland;
use app\models\Accounts;
use app\models\OrdersStatuses;
use app\models\DeliveryTypes;
use app\models\Payments;
use app\models\OrderSync;
class SettingsController  extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;       
        return parent::beforeAction($action);
    }


    public function actionIndex(){
        if(!isset($_SESSION['clientId'])){
            return $this->redirect('/accounts');                
        }else{
            $clientId = $_SESSION['clientId'];
        }
        
        $account = new \app\models\Accounts;
        $account = ($account->findAll(['uniqueAccountHash'=>$clientId])==null)?null:$account->findAll(['uniqueAccountHash'=>$clientId]);
        
        if($account == null)
            return $this->redirect('/accounts');
        
        $warning= false;
        
        $status =  new \app\models\OrdersStatuses;
        $status = ($status::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$status::findAll(["uniqueAccountHash" => $clientId]);
        $delivery = new \app\models\DeliveryTypes;
        $delivery = ($delivery::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$delivery::findAll(["uniqueAccountHash" => $clientId]);

        $payments =  new \app\models\Payments();
        $payments = ($payments ::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$payments ::findAll(["uniqueAccountHash" => $clientId]);
        
        if($payments==null )$warning['Оплаты']='Не настроено соответствие типов оплат';
        if($delivery == null)$warning['Доставки']='Не настроено соответствие типов доставок'; 
        if( $status==null)$warning['Статусы']='Не настроено соответствие статусов заказов';
        
        $order_sync = new \app\models\OrderSync;
        $order_sync = ($order_sync->findOne(['uniqueAccountHash' => $clientId]) == null)? null : $order_sync->findOne(['uniqueAccountHash' => $clientId]);
     if($order_sync != null){
            if($warning!=FALSE){       
                $order_sync->warning = TRUE;
                $order_sync->save();
            }else{
                $order_sync->warning = FALSE;
                $order_sync->save();
            }
        }        
        return $this->render('settings',['warning'=>$warning]);
    }


    public function actionStatus()
    {                            
         if(!isset($_SESSION['clientId']) || $_SESSION['clientId'] ==''){
            return $this->redirect('/accounts');                
        }else{
            $clientId = $_SESSION['clientId'];
        }
        
        if(isset($_GET['delete']) and $_GET['delete']  == true){
            $model = new \app\models\OrdersStatuses;
            $model->deleteAll(['uniqueAccountHash'=>$clientId]);
            return $this->redirect('/settings/status');  
            
        }                
        $model = new \app\models\OrdersStatuses;
        $model = ($model::findAll(["uniqueAccountHash" => $clientId]) == null)?null:$model::findAll(["uniqueAccountHash" => $clientId]);

        $retailStatuses = [];
        $storelandStatuses = [];
        $account= \app\models\Accounts::getModel();
        $apiUrl = $account['retailAPIURL'];
        $apiKey = $account['retailAPIKey'];
        $retailCRM = new RetailCRM($apiUrl, $apiKey);
        $retailStatuses =  $retailCRM->getOrdersStatuses();
        $shops = $retailCRM->getShops();
        $storelandURL = $account['storelandAPIURL'];
        $storelandKey = $account['storelandAPIToken'];        
        $storeland = new \app\models\Storeland($storelandURL,$storelandKey);
        $storelandStatuses = $storeland->getOrdersStatuses();
        
        $retailStatusesPOST = \Yii::$app->request->post('retailStatuses', '') ; 
        $storelandStatusesPOST = \Yii::$app->request->post('storelandStatuses', '');
        
        if($clientId!=''&& $retailStatusesPOST != '' && $storelandStatusesPOST != '' && count($storelandStatusesPOST)== count($retailStatusesPOST)){

        ////////////////////////////////////////////////////////////////////////////////////////////////////////
        //
        //


            $i = 0;
            
            foreach($retailStatusesPOST as $storeland => $retail ){
                $model = new \app\models\OrdersStatuses;
                $model = ($model::findOne(["uniqueAccountHash" => $clientId,'storelandStatus'=>$storeland]) == null)?'':$model::findOne(["uniqueAccountHash" => $clientId,'storelandStatus'=>$storeland]);
                if($model==''){
                    $model = new \app\models\OrdersStatuses;
                    $model->retailStatus = strval($retail);
                    $model->storelandStatus = strval($storeland);
                    $model->uniqueAccountHash = $clientId;
                    $model->save();
                }else{
                   $model->retailStatus = strval($retail);     
                   $model->save();
                }
                
            }
            return $this->redirect('/settings/status?save=true');
        }
        else{
            $save = false;
            return $this->render('statuses',[
                'retailStatuses' => $retailStatuses,    
                'storelandStatuses' =>$storelandStatuses,            
                'shops' => $shops,
                'save' => $save ,
                'model' =>$model
                ]);
        }

        return $this->render('statuses',[
            'retailStatuses' => $retailStatuses,    
            'storelandStatuses' =>$storelandStatuses,            
            'shops' => $shops,
            'save' => 'noneed',
            'model' =>$model
            ]);        
    }


    public function actionDelivery()
       {                            
        if(!isset($_SESSION['clientId']) || $_SESSION['clientId'] ==''){
            return $this->redirect('/accounts');                
        }else{
            $clientId = $_SESSION['clientId'];
        }
        
        /*if(isset($_GET['delete']) and $_GET['delete']  == true){
            $model = new \app\models\DeliveryTypes();
            $model->deleteAll(['uniqueAccountHash'=>$clientId]);
            return $this->redirect('/settings/delivery');              
        }*/
        $model = new \app\models\DeliveryTypes();
        $model = ($model::findAll(["uniqueAccountHash" => $clientId]) == null) ? null : $model::findAll(["uniqueAccountHash" => $clientId]);
        $retailDeliveryTypes = [];
        $storelandDeliveryTypes = [];
        $account= \app\models\Accounts::getModel();
        $apiUrl = $account['retailAPIURL'];
        $apiKey = $account['retailAPIKey'];
        $retailCRM = new RetailCRM($apiUrl, $apiKey);
        $retailDeliveryTypes =  $retailCRM->getDeliveryTypes();
        $shops = $retailCRM->getShops();
        $storelandURL = $account['storelandAPIURL'];
        $storelandKey = $account['storelandAPIToken'];        
        $storeland = new \app\models\Storeland($storelandURL,$storelandKey);
        $storelandDeliveryTypes = $storeland->getDeliveryTypes();

        /*if($model != null && count($storelandDeliveryTypes) != count($model)) {
              $model = new \app\models\DeliveryTypes();
            $model->deleteAll(['uniqueAccountHash'=>$clientId]);
            return $this->redirect('/settings/delivery');      
        }*/
        $retailDeliveryTypesPOST = \Yii::$app->request->post('retailDeliveryTypes', '') ; 
        $storelandDeliveryTypesPOST = \Yii::$app->request->post('storelandDeliveryTypes', '');
        if($clientId!=''&& $retailDeliveryTypesPOST != '' && $storelandDeliveryTypesPOST != '' && count($retailDeliveryTypesPOST)== count($storelandDeliveryTypesPOST)){
            $i = 0;
            foreach($retailDeliveryTypesPOST as $storeland => $retail ){
                $model = new DeliveryTypes();
                $deliveryType = ($model::findOne(["uniqueAccountHash" => $clientId,'storelandDeliveryTypes'=>$storeland]) == null)? '':$model::findOne(["uniqueAccountHash" => $clientId,'storelandDeliveryTypes'=>$storeland]);

                if(empty($deliveryType)){


                    //var_dump($retail);
                    $model->retailDeliveryTypes = strval($retail);
                    $model->storelandDeliveryTypes = strval($storeland);
                    $model->uniqueAccountHash = $clientId;
                    $model->save();
                }else{
                    $deliveryType->retailDeliveryTypes = strval($retail);
                    $deliveryType->save();
                }

            }
            return $this->redirect('/settings/delivery?save=true');
        }
        else{
            $save = false;
            return $this->render('delivery',[
                'retailDeliveryTypes' => $retailDeliveryTypes ,    
                'storelandDeliveryTypes' =>$storelandDeliveryTypes ,            
                'shops' => $shops,
                'save' => $save ,
                'model' =>$model
                ]);
        }

        return $this->render('delivery',[
            'retailDeliveryTypes' => $retailDeliveryTypes ,    
            'storelandDeliveryTypes' =>$storelandDeliveryTypes ,               
            'shops' => $shops,
            'save' => 'noneed',
            'model' =>$model
            ]);        
    }


    public function actionPaymentStatuses() {
       if(!isset($_SESSION['clientId']) || $_SESSION['clientId'] ==''){
            return $this->redirect('/accounts');                
        }else{
            $clientId = $_SESSION['clientId'];
        }
        
        if(isset($_GET['delete']) and $_GET['delete']  == true){
            $model = new \app\models\PaymentStatuses();
            $model->deleteAll(['uniqueAccountHash'=>$clientId]);

views/settings/delivery.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $retailDeliveryTypes array */
/* @var $storelandDeliveryTypes array */
/* @var $shops array */
$this->title = Yii::t('app', 'Соответствие типов доставки ');
?>
<div class="sites-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php 
    if(!$retailDeliveryTypes){?>
        <div class = 'alert-danger'>
            <h1>Не удалось получить типы доставок из retailCrm</h1>
            <p class = 'lead'>
                Возможно,стоит проверить Ваш АПИ-ключ
            </p>    
        </div>
     </div> 
    <?php    
       
        }else{
    ?>
    <?php 
    if(!$storelandDeliveryTypes){?>
        <div class = 'alert-danger'>
            <h1>Не удалось получить типы доставок из Storeland</h1>
            <p class = 'lead'>
                <a href="http://storeland.imb-service.ru/info">Пройдитесь по пунктам документации </a> и проверьте, всё ли правильно Вы делаете
            </p>    
        </div>    
</div>
    <?php           
        }else{ 
            ?>   
    
     <div class="row">
        <div class="col-lg-12">
            <?php 
            $save = (isset($_GET['save']))? (($_GET['save'] == 'true')? 'true' : ''):'';
                echo ($save == 'true')?
                     '<div class="alert alert-success">
                        <h1>Изменения успешно применены</h1>
                    </div>
            ' : ''  ;
                   echo ($save == 'false')?
                    '<div class="alert alert-danger">
                        <h1>Не удалось применить изменения</h1>
                    </div>
            ' : ''  ;
             
            ?>
            
            </div>
            <div class="sites-form">
                <?= Html::beginForm(['/settings/delivery'], 'post') ?>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Типы доставок в Storeland</th>
                            <th>Типы доставок в retailCRM</th>
                        </tr>
                    </thead>
                    <tbody>

                    <?php foreach ($storelandDeliveryTypes as $key => $value) { ?>
                        <tr>
                            <td>
                                <?= $value ?>
                                <?= Html::hiddenInput('storelandDeliveryTypes[]', $key ) ?>
                            </td>
                            <td>
                                <?php
                                $options = ['class' => 'form-control'];
                                if($model != ''){                                    
                                    foreach($model as $deliveryloc){
                                       
                                        if($deliveryloc->attributes['storelandDeliveryTypes'] == $key){
                                            $options = ['class' => 'form-control','options' =>[$deliveryloc->attributes['retailDeliveryTypes'] =>['selected' => true]]];
                                            break;
                                        }else{
                                            $options = ['class' => 'form-control'];
                                        }
                                    }
                                }
                                ?>
                                
                                <?=  ($model == '')?                                    
                                        Html::dropDownList('retailDeliveryTypes['.$key.']',[],$retailDeliveryTypes,$options):
                                        Html::dropDownList('retailDeliveryTypes['.$key.']',[],$retailDeliveryTypes,$options);                                     
                                ?> 
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn btn-success']) ?>
                </div>
                <div class="form-group">
                    <a onclick="confirm_delete()"class ="btn btn btn-danger">
                        Очистить настройки 
                    </a>
                </div>
                <script>
                    function confirm_delete(){
                        var isAdmin = confirm("Вы дейстительно хотите очистить соответсия?");
                        if(isAdmin == true){
                            window.location.reload(true);
                            window.location.replace('http://storeland.imb-service.ru/settings/delivery?delete=true');
                        }
                    }
                </script>
            </div>                
        </div>             
    </div>
</div>

            
        <?php }
    }
    ?>
    
  <?php
    require_once ROOT.'views/layouts/active.php';

views/settings/payment_statuses.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $retailPaymentStatuses array */
/* @var $storelandPaymentStatuses array */
/* @var $shops array */
$this->title = Yii::t('app', 'Соответствие статусов оплаты ');
?>
<div class="sites-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php 
    if(!$retailPaymentStatuses){?>
        <div class = 'alert-danger'>
            <h1>Не удалось получить типы оплат из retailCRM </h1>
            <p class = 'lead'>
                Возможно,стоит проверить Ваш АПИ-ключ 
            </p>    
        </div>  
    </div> 
    <?php    
       
        }else{
    ?>

  
    
     <div class="row">
        <div class="col-lg-12">
            <?php 
            $save = (isset($_GET['save']))? (($_GET['save'] == 'true')? 'true' : ''):'';
                echo ($save == 'true')?
                     '<div class="alert alert-success">
                        <h1>Изменения успешно применены</h1>
                    </div>
            ' : ''  ;
                   echo ($save == 'false')?
                    '<div class="alert alert-danger">
                        <h1>Не удалось применить изменения</h1>
                    </div>
            ' : ''  ;
             
            ?>
            
            </div>
            <div class="sites-form">
                <?= Html::beginForm(['/settings/payment-statuses'], 'post') ?>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Типы доставок в Storeland</th>
                            <th>Типы доставок в retailCRM</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($storelandPaymentStatuses as $key => $value) { ?>
                        <tr>
                            <td>
                                <?= $value ?>
                                <?= Html::hiddenInput('storelandPaymentStatuses[]', $key ) ?>
                            </td>
                            <td>
                                <?php
                                $options = ['class' => 'form-control'];
                                if($model != ''){                                    
                                    foreach($model as $paymentloc){
                                       
                                        if($paymentloc->attributes['storelandPaymentStatus'] == $key){
                                            $options = ['class' => 'form-control ','options' =>[$paymentloc->attributes['retailPaymentStatus'] =>['selected' => true]]];
                                            break;
                                        }else{
                                            $options = ['class' => 'form-control'];
                                        }
                                    }
                                }
                                ?>
                                
                                <?=  ($model == '')?                                    
                                        Html::dropDownList('retailPaymentStatuses['.$key.']',[],$retailPaymentStatuses,$options):
                                        Html::dropDownList('retailPaymentStatuses['.$key.']',[],$retailPaymentStatuses,$options);                                     
                                ?> 
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                </div>
                <div class="form-group">
                    <a onclick="confirm_delete()"class ="btn btn-danger">
                        Очистить настройки 
                    </a>
                </div>
                <script>
                    function confirm_delete(){
                        var isAdmin = confirm("Вы дейстительно хотите очистить соответсия?");
                        if(isAdmin == true){
                            window.location.reload(true);
                            window.location.replace('http://storeland.imb-service.ru/settings/payment-statuses?delete=true');
                        }
                    }
                </script>
            </div>                
        </div>             
    </div>
</div>

<?php
    }
    ?>
    
<?php
if(!empty($_SESSION['freeze']) && $_SESSION['freeze']===1):    
?>

<div id="freeze" class="modal fade bd-example-modal-lg" keyboard="false" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="content modal-main alert">
                <h1>
                    Ваш аккаунт заморожен
                </h1>

                <p>
                    Для разморозки необходимо пополнить счёт
                </p>
            </div>
        </div>
    </div>
</div>

<script>
window.onload = function() {
    $('#freeze').modal({
          backdrop: 'static',
          keyboard: false
    });
};

</script>
<?php endif; ?>


<?php if(isset($_SESSION['active']) && $_SESSION['active']===0 && (empty($_SESSION['freeze']) || $_SESSION['freeze']===0) ):  ?>

<div id="active" class="modal fade bd-example-modal-lg" keyboard="false" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="content modal-main alert">
                <h1>
                    Ваш аккаунт выключен
                </h1>

                <p>
                    Синхронизация заказов проводиться не будет
                </p>
            </div>
        </div>
    </div>
</div>

<script>
window.onload = function() {
    $('#active').modal('show');
};

</script>
<?php endif; ?>


views/settings/payments.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $retailPaymentTypes array */
/* @var $storelandPaymentTypes array */
/* @var $shops array */
$this->title = Yii::t('app', 'Соответствие типов оплаты ');
?>
<div class="sites-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php 
    if(!$retailPaymentTypes){?>
        <div class = 'alert-danger'>
            <h1>Не удалось получить типы оплат из retailCRM </h1>
            <p class = 'lead'>
                Возможно,стоит проверить Ваш АПИ-ключ 
            </p>    
        </div>       
    </div> 
    <?php    
       
        }else{
    ?>
    <?php 
    if(!$storelandPaymentTypes){?>
        <div class = 'alert-danger'>
            <h1>Не удалось получить типы оплат из Storeland </h1>
            <p class = 'lead'>
                <a href="http://storeland.imb-service.ru/info">Пройдитесь по пунктам документации </a> и проверьте, всё ли правильно Вы делаете
            </p>    
        </div>
    </div> 
    <?php           
        }else{ 
            ?>   
    
     <div class="row">
        <div class="col-lg-12">
            <?php 
            $save = (isset($_GET['save']))? (($_GET['save'] == 'true')? 'true' : ''):'';
                echo ($save == 'true')?
                     '<div class="alert alert-success">
                        <h1>Изменения успешно применены</h1>
                    </div>
            ' : ''  ;
                   echo ($save == 'false')?
                    '<div class="alert alert-danger">
                        <h1>Не удалось применить изменения</h1>
                    </div>
            ' : ''  ;
             
            ?>
            
            </div>
            <div class="sites-form">
                <?= Html::beginForm(['/settings/payments'], 'post') ?>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Типы доставок в Storeland</th>
                            <th>Типы доставок в retailCRM</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($storelandPaymentTypes as $key => $value) { ?>
                        <tr>
                            <td>
                                <?= $value ?>
                                <?= Html::hiddenInput('storelandPaymentTypes[]', $key ) ?>
                            </td>
                            <td>
                                <?php
                                $options = ['class' => 'form-control'];
                                if($model != ''){                                    
                                    foreach($model as $paymentloc){
                                       
                                        if($paymentloc->attributes['storelandPaymentTypes'] == $key){
                                            $options = ['class' => 'form-control ','options' =>[$paymentloc->attributes['retailPaymentTypes'] =>['selected' => true]]];
                                            break;
                                        }else{
                                            $options = ['class' => 'form-control'];
                                        }
                                    }
                                }
                                ?>
                                
                                <?=  ($model == '')?                                    
                                        Html::dropDownList('retailPaymentTypes['.$key.']',[],$retailPaymentTypes,$options):
                                        Html::dropDownList('retailPaymentTypes['.$key.']',[],$retailPaymentTypes,$options);                                     
                                ?> 
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
                </div>
                <div class="form-group">
                    <a onclick="confirm_delete()"class ="btn btn-danger">
                        Очистить настройки 
                    </a>
                </div>
                <script>
                    function confirm_delete(){
                        var isAdmin = confirm("Вы дейстительно хотите очистить соответсия?");
                        if(isAdmin == true){
                            window.location.reload(true);
                            window.location.replace('http://storeland.imb-service.ru/settings/payments?delete=true');
                        }
                    }
                </script>
            </div>                
        </div>             
    </div>
</div>

            
        <?php }
    }
    ?>
    
<?php
if(!empty($_SESSION['freeze']) && $_SESSION['freeze']===1):    
?>

<div id="freeze" class="modal fade bd-example-modal-lg" keyboard="false" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="content modal-main alert">
                <h1>
                    Ваш аккаунт заморожен
                </h1>

                <p>
                    Для разморозки необходимо пополнить счёт
                </p>
            </div>
        </div>
    </div>
</div>

<script>
window.onload = function() {
    $('#freeze').modal({
          backdrop: 'static',
          keyboard: false
    });
};

</script>
<?php endif; ?>


<?php if(isset($_SESSION['active']) && $_SESSION['active']===0 && (empty($_SESSION['freeze']) || $_SESSION['freeze']===0) ):  ?>

<div id="active" class="modal fade bd-example-modal-lg" keyboard="false" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="content modal-main alert">
                <h1>
                    Ваш аккаунт выключен
                </h1>

                <p>
                    Синхронизация заказов проводиться не будет
                </p>
            </div>
        </div>
    </div>
</div>

<script>
window.onload = function() {
    $('#active').modal('show');
};

</script>
<?php endif; ?>
